spring:
  datasource:
    url: jdbc:mysql://192.168.75.128:3306/jpa?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update


  redis:
    host: 192.168.75.128



